services:
  api:
    build: .
    container_name: API_Biblioteca
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    # NOTA EL CAMBIO A API.API:app
    command: uvicorn API.API:app --host 0.0.0.0 --port 5000 --reload